apiVersion: v1
kind: ConfigMap
metadata:
  name: wb-tech-l0-cfg
data:
  PG_PASSWORD: wildberriestech1553
  SERVICE_PORT: 8081
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: wb-tech-l0
  name: wb-tech-l0
spec:
  containers:
  - name: db
    image: localhost/wb-tech-l0-db
    env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: wb-tech-l0-cfg
          key: PG_PASSWORD
          optional: false
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: db-pvc
  - name: nats-streaming
    image: docker.io/library/nats-streaming:0.25.5-alpine3.18
    ports:
    - containerPort: 4222
  - name: app
    image: localhost/wb-tech-l0-app
    envFrom:
    - configMapRef:
        name: wb-tech-l0-cfg
        optional: false
    ports:
    - containerPort: 8081
  volumes:
  - name: db-pvc
    persistentVolumeClaim:
      claimName: wb-tech-l0-db
